# Laboratory Task 5 – Tensor Manipulations

In [1]:
# 1. Standard Imports
import torch
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# 2. Create the set_seed function
def set_seed(seed: int):
    """Sets the random seed for PyTorch and NumPy."""
    torch.manual_seed(seed)
    np.random.seed(seed)

In [4]:
# 3. Create a seeded NumPy array
set_seed(42)
arr = np.random.randint(0, 5, size=6)
print(f"NumPy array 'arr': {arr}\n")

NumPy array 'arr': [3 4 2 4 4 1]



In [6]:
# 4. Create a tensor 'x'
x = torch.from_numpy(arr)
print(f"Tensor 'x': {x}\n")

Tensor 'x': tensor([3, 4, 2, 4, 4, 1], dtype=torch.int32)



In [7]:
# 5. Change dtype to int64
x = x.to(torch.int64)
print(f"Dtype of 'x': {x.dtype}\n")

Dtype of 'x': torch.int64



In [9]:
# 6. Reshape x into a 3x2 tensor
x_reshaped = x.reshape(3, 2)
print(f"Reshaped 'x' (3x2):\n{x_reshaped}\n")

Reshaped 'x' (3x2):
tensor([[3, 4],
        [2, 4],
        [4, 1]])



In [10]:
# 7. Get the right-hand column
right_column = x_reshaped[:, 1]
print(f"Right-hand column: {right_column}\n")

Right-hand column: tensor([4, 4, 1])



In [11]:
# 8. Get square values
x_squared = x_reshaped ** 2
print(f"Squared values:\n{x_squared}\n")

Squared values:
tensor([[ 9, 16],
        [ 4, 16],
        [16,  1]])



In [12]:
# 9. Create tensor y for matrix multiplication
set_seed(42)
y = torch.randint(0, 5, (2, 3), dtype=torch.int64)
print(f"Tensor 'y' (2x3):\n{y}\n")

Tensor 'y' (2x3):
tensor([[2, 2, 1],
        [4, 1, 0]])



In [13]:
# 10. Find the matrix product
matrix_product = torch.matmul(x_reshaped, y)
print(f"Matrix product of x and y:\n{matrix_product}\n")

Matrix product of x and y:
tensor([[22, 10,  3],
        [20,  8,  2],
        [12,  9,  4]])



### Reflection
* Deep learning is fundamentally about performing mathematical operations on multi-dimensional arrays, or **tensors**.

* This lab covers the essential "data wrangling" skills required for any deep learning task, such as creating tensors, changing their data types `(dtype)`, and altering their shape `(reshape)`.

* Mastering tensor operations like selecting specific elements (slicing) and performing matrix multiplication is a critical prerequisite for building any neural network.